// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source=../../repo/contracts.go -destination=./mocks_test.go -package=installment_test
//

// Package installment_test is a generated GoMock package.
package installment_test

import (
	context "context"
	article "go-boilerplate/internal/dto/article"
	bankstatement "go-boilerplate/internal/dto/bankstatement"
	installment "go-boilerplate/internal/dto/installment"
	translation "go-boilerplate/internal/dto/translation"
	user "go-boilerplate/internal/dto/user"
	entity "go-boilerplate/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, req translation.HistoryRequest) ([]entity.Translation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, req)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, req)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(arg0 context.Context, arg1 *entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), arg0, arg1)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 *entity.Translation) (*entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(*entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepo) Create(ctx context.Context, arg1 *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepo)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockUserRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepo)(nil).Delete), ctx, id)
}

// EmailExists mocks base method.
func (m *MockUserRepo) EmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailExists indicates an expected call of EmailExists.
func (mr *MockUserRepoMockRecorder) EmailExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailExists", reflect.TypeOf((*MockUserRepo)(nil).EmailExists), ctx, email)
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id uint) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockUserRepo) List(ctx context.Context, req user.ListRequest) ([]*entity.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]*entity.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepoMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepo)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockUserRepo) Update(ctx context.Context, arg1 *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepoMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepo)(nil).Update), ctx, arg1)
}

// MockRoleRepo is a mock of RoleRepo interface.
type MockRoleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepoMockRecorder
	isgomock struct{}
}

// MockRoleRepoMockRecorder is the mock recorder for MockRoleRepo.
type MockRoleRepoMockRecorder struct {
	mock *MockRoleRepo
}

// NewMockRoleRepo creates a new mock instance.
func NewMockRoleRepo(ctrl *gomock.Controller) *MockRoleRepo {
	mock := &MockRoleRepo{ctrl: ctrl}
	mock.recorder = &MockRoleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepo) EXPECT() *MockRoleRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoleRepo) Create(ctx context.Context, role *entity.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepoMockRecorder) Create(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepo)(nil).Create), ctx, role)
}

// Delete mocks base method.
func (m *MockRoleRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRoleRepo) GetByID(ctx context.Context, id uint) (*entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleRepo)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockRoleRepo) GetByName(ctx context.Context, name string) (*entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockRoleRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockRoleRepo)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockRoleRepo) List(ctx context.Context) ([]*entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockRoleRepo) Update(ctx context.Context, role *entity.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepoMockRecorder) Update(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepo)(nil).Update), ctx, role)
}

// UpdatePermissions mocks base method.
func (m *MockRoleRepo) UpdatePermissions(ctx context.Context, roleID uint, permissionIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermissions", ctx, roleID, permissionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePermissions indicates an expected call of UpdatePermissions.
func (mr *MockRoleRepoMockRecorder) UpdatePermissions(ctx, roleID, permissionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermissions", reflect.TypeOf((*MockRoleRepo)(nil).UpdatePermissions), ctx, roleID, permissionIDs)
}

// MockPermissionRepo is a mock of PermissionRepo interface.
type MockPermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepoMockRecorder
	isgomock struct{}
}

// MockPermissionRepoMockRecorder is the mock recorder for MockPermissionRepo.
type MockPermissionRepoMockRecorder struct {
	mock *MockPermissionRepo
}

// NewMockPermissionRepo creates a new mock instance.
func NewMockPermissionRepo(ctrl *gomock.Controller) *MockPermissionRepo {
	mock := &MockPermissionRepo{ctrl: ctrl}
	mock.recorder = &MockPermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepo) EXPECT() *MockPermissionRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionRepo) Create(ctx context.Context, permission *entity.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepoMockRecorder) Create(ctx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepo)(nil).Create), ctx, permission)
}

// Delete mocks base method.
func (m *MockPermissionRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionRepo)(nil).Delete), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockPermissionRepo) GetByIDs(ctx context.Context, ids []uint) ([]*entity.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*entity.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockPermissionRepoMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockPermissionRepo)(nil).GetByIDs), ctx, ids)
}

// GetByName mocks base method.
func (m *MockPermissionRepo) GetByName(ctx context.Context, name string) (*entity.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPermissionRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPermissionRepo)(nil).GetByName), ctx, name)
}

// IsAssignedToAnyRole mocks base method.
func (m *MockPermissionRepo) IsAssignedToAnyRole(ctx context.Context, permissionID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAssignedToAnyRole", ctx, permissionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAssignedToAnyRole indicates an expected call of IsAssignedToAnyRole.
func (mr *MockPermissionRepoMockRecorder) IsAssignedToAnyRole(ctx, permissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAssignedToAnyRole", reflect.TypeOf((*MockPermissionRepo)(nil).IsAssignedToAnyRole), ctx, permissionID)
}

// List mocks base method.
func (m *MockPermissionRepo) List(ctx context.Context) ([]*entity.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPermissionRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionRepo)(nil).List), ctx)
}

// MockRefreshTokenRepo is a mock of RefreshTokenRepo interface.
type MockRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepoMockRecorder is the mock recorder for MockRefreshTokenRepo.
type MockRefreshTokenRepoMockRecorder struct {
	mock *MockRefreshTokenRepo
}

// NewMockRefreshTokenRepo creates a new mock instance.
func NewMockRefreshTokenRepo(ctrl *gomock.Controller) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepo) Create(ctx context.Context, token *entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepoMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Create), ctx, token)
}

// DeleteByToken mocks base method.
func (m *MockRefreshTokenRepo) DeleteByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByToken indicates an expected call of DeleteByToken.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByToken", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByToken), ctx, token)
}

// DeleteByUserID mocks base method.
func (m *MockRefreshTokenRepo) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockRefreshTokenRepo) GetByToken(ctx context.Context, token string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockRefreshTokenRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockRefreshTokenRepo)(nil).GetByToken), ctx, token)
}

// MockMediaRepo is a mock of MediaRepo interface.
type MockMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepoMockRecorder
	isgomock struct{}
}

// MockMediaRepoMockRecorder is the mock recorder for MockMediaRepo.
type MockMediaRepoMockRecorder struct {
	mock *MockMediaRepo
}

// NewMockMediaRepo creates a new mock instance.
func NewMockMediaRepo(ctrl *gomock.Controller) *MockMediaRepo {
	mock := &MockMediaRepo{ctrl: ctrl}
	mock.recorder = &MockMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepo) EXPECT() *MockMediaRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMediaRepo) Create(ctx context.Context, media *entity.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMediaRepoMockRecorder) Create(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMediaRepo)(nil).Create), ctx, media)
}

// Delete mocks base method.
func (m *MockMediaRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaRepo)(nil).Delete), ctx, id)
}

// DeleteByAttachable mocks base method.
func (m *MockMediaRepo) DeleteByAttachable(ctx context.Context, attachableType string, attachableID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAttachable", ctx, attachableType, attachableID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAttachable indicates an expected call of DeleteByAttachable.
func (mr *MockMediaRepoMockRecorder) DeleteByAttachable(ctx, attachableType, attachableID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAttachable", reflect.TypeOf((*MockMediaRepo)(nil).DeleteByAttachable), ctx, attachableType, attachableID)
}

// GetByAttachable mocks base method.
func (m *MockMediaRepo) GetByAttachable(ctx context.Context, attachableType string, attachableID uint, collection string) ([]*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAttachable", ctx, attachableType, attachableID, collection)
	ret0, _ := ret[0].([]*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAttachable indicates an expected call of GetByAttachable.
func (mr *MockMediaRepoMockRecorder) GetByAttachable(ctx, attachableType, attachableID, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAttachable", reflect.TypeOf((*MockMediaRepo)(nil).GetByAttachable), ctx, attachableType, attachableID, collection)
}

// GetByID mocks base method.
func (m *MockMediaRepo) GetByID(ctx context.Context, id uint) (*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMediaRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockMediaRepo) Update(ctx context.Context, media *entity.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMediaRepoMockRecorder) Update(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMediaRepo)(nil).Update), ctx, media)
}

// MockEmailVerificationRepo is a mock of EmailVerificationRepo interface.
type MockEmailVerificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepoMockRecorder
	isgomock struct{}
}

// MockEmailVerificationRepoMockRecorder is the mock recorder for MockEmailVerificationRepo.
type MockEmailVerificationRepoMockRecorder struct {
	mock *MockEmailVerificationRepo
}

// NewMockEmailVerificationRepo creates a new mock instance.
func NewMockEmailVerificationRepo(ctrl *gomock.Controller) *MockEmailVerificationRepo {
	mock := &MockEmailVerificationRepo{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepo) EXPECT() *MockEmailVerificationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailVerificationRepo) Create(ctx context.Context, verification *entity.EmailVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, verification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationRepoMockRecorder) Create(ctx, verification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationRepo)(nil).Create), ctx, verification)
}

// DeleteByUserID mocks base method.
func (m *MockEmailVerificationRepo) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockEmailVerificationRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockEmailVerificationRepo)(nil).DeleteByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockEmailVerificationRepo) GetByToken(ctx context.Context, token string) (*entity.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*entity.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockEmailVerificationRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockEmailVerificationRepo)(nil).GetByToken), ctx, token)
}

// GetLatestByUserID mocks base method.
func (m *MockEmailVerificationRepo) GetLatestByUserID(ctx context.Context, userID uint) (*entity.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUserID indicates an expected call of GetLatestByUserID.
func (mr *MockEmailVerificationRepoMockRecorder) GetLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUserID", reflect.TypeOf((*MockEmailVerificationRepo)(nil).GetLatestByUserID), ctx, userID)
}

// MarkAsUsed mocks base method.
func (m *MockEmailVerificationRepo) MarkAsUsed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockEmailVerificationRepoMockRecorder) MarkAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockEmailVerificationRepo)(nil).MarkAsUsed), ctx, id)
}

// MockPasswordResetRepo is a mock of PasswordResetRepo interface.
type MockPasswordResetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepoMockRecorder
	isgomock struct{}
}

// MockPasswordResetRepoMockRecorder is the mock recorder for MockPasswordResetRepo.
type MockPasswordResetRepoMockRecorder struct {
	mock *MockPasswordResetRepo
}

// NewMockPasswordResetRepo creates a new mock instance.
func NewMockPasswordResetRepo(ctrl *gomock.Controller) *MockPasswordResetRepo {
	mock := &MockPasswordResetRepo{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepo) EXPECT() *MockPasswordResetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetRepo) Create(ctx context.Context, reset *entity.PasswordReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetRepoMockRecorder) Create(ctx, reset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetRepo)(nil).Create), ctx, reset)
}

// DeleteByUserID mocks base method.
func (m *MockPasswordResetRepo) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockPasswordResetRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockPasswordResetRepo)(nil).DeleteByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockPasswordResetRepo) GetByToken(ctx context.Context, token string) (*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockPasswordResetRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockPasswordResetRepo)(nil).GetByToken), ctx, token)
}

// MarkAsUsed mocks base method.
func (m *MockPasswordResetRepo) MarkAsUsed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockPasswordResetRepoMockRecorder) MarkAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockPasswordResetRepo)(nil).MarkAsUsed), ctx, id)
}

// MockProfileRepo is a mock of ProfileRepo interface.
type MockProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepoMockRecorder
	isgomock struct{}
}

// MockProfileRepoMockRecorder is the mock recorder for MockProfileRepo.
type MockProfileRepoMockRecorder struct {
	mock *MockProfileRepo
}

// NewMockProfileRepo creates a new mock instance.
func NewMockProfileRepo(ctrl *gomock.Controller) *MockProfileRepo {
	mock := &MockProfileRepo{ctrl: ctrl}
	mock.recorder = &MockProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepo) EXPECT() *MockProfileRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProfileRepo) Create(ctx context.Context, profile *entity.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProfileRepoMockRecorder) Create(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProfileRepo)(nil).Create), ctx, profile)
}

// GetByUserID mocks base method.
func (m *MockProfileRepo) GetByUserID(ctx context.Context, userID uint) (*entity.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockProfileRepoMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockProfileRepo)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockProfileRepo) Update(ctx context.Context, profile *entity.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProfileRepoMockRecorder) Update(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProfileRepo)(nil).Update), ctx, profile)
}

// Upsert mocks base method.
func (m *MockProfileRepo) Upsert(ctx context.Context, profile *entity.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProfileRepoMockRecorder) Upsert(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProfileRepo)(nil).Upsert), ctx, profile)
}

// MockArticleRepo is a mock of ArticleRepo interface.
type MockArticleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepoMockRecorder
	isgomock struct{}
}

// MockArticleRepoMockRecorder is the mock recorder for MockArticleRepo.
type MockArticleRepoMockRecorder struct {
	mock *MockArticleRepo
}

// NewMockArticleRepo creates a new mock instance.
func NewMockArticleRepo(ctrl *gomock.Controller) *MockArticleRepo {
	mock := &MockArticleRepo{ctrl: ctrl}
	mock.recorder = &MockArticleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepo) EXPECT() *MockArticleRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockArticleRepo) Create(ctx context.Context, arg1 *entity.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockArticleRepoMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArticleRepo)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockArticleRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockArticleRepo) GetByID(ctx context.Context, id uint) (*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockArticleRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockArticleRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockArticleRepo) List(ctx context.Context, req article.ListRequest) ([]*entity.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]*entity.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockArticleRepoMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArticleRepo)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockArticleRepo) Update(ctx context.Context, arg1 *entity.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockArticleRepoMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArticleRepo)(nil).Update), ctx, arg1)
}

// MockBankRepo is a mock of BankRepo interface.
type MockBankRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBankRepoMockRecorder
	isgomock struct{}
}

// MockBankRepoMockRecorder is the mock recorder for MockBankRepo.
type MockBankRepoMockRecorder struct {
	mock *MockBankRepo
}

// NewMockBankRepo creates a new mock instance.
func NewMockBankRepo(ctrl *gomock.Controller) *MockBankRepo {
	mock := &MockBankRepo{ctrl: ctrl}
	mock.recorder = &MockBankRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankRepo) EXPECT() *MockBankRepoMockRecorder {
	return m.recorder
}

// GetByCode mocks base method.
func (m *MockBankRepo) GetByCode(ctx context.Context, code string) (*entity.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*entity.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockBankRepoMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockBankRepo)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockBankRepo) GetByID(ctx context.Context, id uint) (*entity.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBankRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBankRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockBankRepo) List(ctx context.Context) ([]*entity.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBankRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBankRepo)(nil).List), ctx)
}

// MockBankStatementRepo is a mock of BankStatementRepo interface.
type MockBankStatementRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBankStatementRepoMockRecorder
	isgomock struct{}
}

// MockBankStatementRepoMockRecorder is the mock recorder for MockBankStatementRepo.
type MockBankStatementRepoMockRecorder struct {
	mock *MockBankStatementRepo
}

// NewMockBankStatementRepo creates a new mock instance.
func NewMockBankStatementRepo(ctrl *gomock.Controller) *MockBankStatementRepo {
	mock := &MockBankStatementRepo{ctrl: ctrl}
	mock.recorder = &MockBankStatementRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankStatementRepo) EXPECT() *MockBankStatementRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBankStatementRepo) Create(ctx context.Context, stmt *entity.BankStatement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBankStatementRepoMockRecorder) Create(ctx, stmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBankStatementRepo)(nil).Create), ctx, stmt)
}

// Delete mocks base method.
func (m *MockBankStatementRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBankStatementRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBankStatementRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBankStatementRepo) GetByID(ctx context.Context, id uint) (*entity.BankStatement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.BankStatement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBankStatementRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBankStatementRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockBankStatementRepo) List(ctx context.Context, req bankstatement.ListRequest) ([]*entity.BankStatement, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]*entity.BankStatement)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockBankStatementRepoMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBankStatementRepo)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockBankStatementRepo) Update(ctx context.Context, stmt *entity.BankStatement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, stmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBankStatementRepoMockRecorder) Update(ctx, stmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBankStatementRepo)(nil).Update), ctx, stmt)
}

// MockLineItemRepo is a mock of LineItemRepo interface.
type MockLineItemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLineItemRepoMockRecorder
	isgomock struct{}
}

// MockLineItemRepoMockRecorder is the mock recorder for MockLineItemRepo.
type MockLineItemRepoMockRecorder struct {
	mock *MockLineItemRepo
}

// NewMockLineItemRepo creates a new mock instance.
func NewMockLineItemRepo(ctrl *gomock.Controller) *MockLineItemRepo {
	mock := &MockLineItemRepo{ctrl: ctrl}
	mock.recorder = &MockLineItemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineItemRepo) EXPECT() *MockLineItemRepoMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockLineItemRepo) BulkCreate(ctx context.Context, items []*entity.LineItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockLineItemRepoMockRecorder) BulkCreate(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockLineItemRepo)(nil).BulkCreate), ctx, items)
}

// DeleteBySource mocks base method.
func (m *MockLineItemRepo) DeleteBySource(ctx context.Context, sourceType string, sourceID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySource", ctx, sourceType, sourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySource indicates an expected call of DeleteBySource.
func (mr *MockLineItemRepoMockRecorder) DeleteBySource(ctx, sourceType, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySource", reflect.TypeOf((*MockLineItemRepo)(nil).DeleteBySource), ctx, sourceType, sourceID)
}

// GetByID mocks base method.
func (m *MockLineItemRepo) GetByID(ctx context.Context, id uint) (*entity.LineItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.LineItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLineItemRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLineItemRepo)(nil).GetByID), ctx, id)
}

// GetBySource mocks base method.
func (m *MockLineItemRepo) GetBySource(ctx context.Context, sourceType string, sourceID uint) ([]*entity.LineItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySource", ctx, sourceType, sourceID)
	ret0, _ := ret[0].([]*entity.LineItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySource indicates an expected call of GetBySource.
func (mr *MockLineItemRepoMockRecorder) GetBySource(ctx, sourceType, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySource", reflect.TypeOf((*MockLineItemRepo)(nil).GetBySource), ctx, sourceType, sourceID)
}

// Update mocks base method.
func (m *MockLineItemRepo) Update(ctx context.Context, item *entity.LineItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLineItemRepoMockRecorder) Update(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLineItemRepo)(nil).Update), ctx, item)
}

// UpdateInstallmentID mocks base method.
func (m *MockLineItemRepo) UpdateInstallmentID(ctx context.Context, itemIDs []uint, installmentID *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstallmentID", ctx, itemIDs, installmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstallmentID indicates an expected call of UpdateInstallmentID.
func (mr *MockLineItemRepoMockRecorder) UpdateInstallmentID(ctx, itemIDs, installmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstallmentID", reflect.TypeOf((*MockLineItemRepo)(nil).UpdateInstallmentID), ctx, itemIDs, installmentID)
}

// MockInstallmentRepo is a mock of InstallmentRepo interface.
type MockInstallmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInstallmentRepoMockRecorder
	isgomock struct{}
}

// MockInstallmentRepoMockRecorder is the mock recorder for MockInstallmentRepo.
type MockInstallmentRepoMockRecorder struct {
	mock *MockInstallmentRepo
}

// NewMockInstallmentRepo creates a new mock instance.
func NewMockInstallmentRepo(ctrl *gomock.Controller) *MockInstallmentRepo {
	mock := &MockInstallmentRepo{ctrl: ctrl}
	mock.recorder = &MockInstallmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstallmentRepo) EXPECT() *MockInstallmentRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstallmentRepo) Create(ctx context.Context, inst *entity.Installment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInstallmentRepoMockRecorder) Create(ctx, inst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstallmentRepo)(nil).Create), ctx, inst)
}

// Delete mocks base method.
func (m *MockInstallmentRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstallmentRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstallmentRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockInstallmentRepo) GetByID(ctx context.Context, id uint) (*entity.Installment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Installment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInstallmentRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInstallmentRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockInstallmentRepo) List(ctx context.Context, req installment.ListRequest) ([]*entity.Installment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]*entity.Installment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockInstallmentRepoMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInstallmentRepo)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockInstallmentRepo) Update(ctx context.Context, inst *entity.Installment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, inst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInstallmentRepoMockRecorder) Update(ctx, inst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInstallmentRepo)(nil).Update), ctx, inst)
}
