// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source=../../../../usecase/contracts.go -destination=./mocks_test.go -package=permission_test
//

// Package permission_test is a generated GoMock package.
package permission_test

import (
	context "context"
	permissiondto "go-boilerplate/internal/dto/permission"
	entity "go-boilerplate/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermission is a mock of Permission interface.
type MockPermission struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionMockRecorder
	isgomock struct{}
}

// MockPermissionMockRecorder is the mock recorder for MockPermission.
type MockPermissionMockRecorder struct {
	mock *MockPermission
}

// NewMockPermission creates a new mock instance.
func NewMockPermission(ctrl *gomock.Controller) *MockPermission {
	mock := &MockPermission{ctrl: ctrl}
	mock.recorder = &MockPermissionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermission) EXPECT() *MockPermissionMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPermission) List(ctx context.Context) ([]*entity.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPermissionMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermission)(nil).List), ctx)
}

// Create mocks base method.
func (m *MockPermission) Create(ctx context.Context, req permissiondto.CreateRequest) (*permissiondto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*permissiondto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermission)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockPermission) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermission)(nil).Delete), ctx, id)
}
