// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../pkg/jwt/jwt.go
//
// Generated by this command:
//
//	mockgen -source=../../../pkg/jwt/jwt.go -destination=mocks_jwt_test.go -package=auth_test
//

// Package auth_test is a generated GoMock package.
package auth_test

import (
	jwt "go-boilerplate/pkg/jwt"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockService) GenerateAccessToken(userID uint, email, role string, permissions []string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, email, role, permissions)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockServiceMockRecorder) GenerateAccessToken(userID, email, role, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockService)(nil).GenerateAccessToken), userID, email, role, permissions)
}

// GenerateRefreshToken mocks base method.
func (m *MockService) GenerateRefreshToken() (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockServiceMockRecorder) GenerateRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockService)(nil).GenerateRefreshToken))
}

// GetAccessExpiry mocks base method.
func (m *MockService) GetAccessExpiry() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessExpiry")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetAccessExpiry indicates an expected call of GetAccessExpiry.
func (mr *MockServiceMockRecorder) GetAccessExpiry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessExpiry", reflect.TypeOf((*MockService)(nil).GetAccessExpiry))
}

// GetRefreshExpiry mocks base method.
func (m *MockService) GetRefreshExpiry() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshExpiry")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetRefreshExpiry indicates an expected call of GetRefreshExpiry.
func (mr *MockServiceMockRecorder) GetRefreshExpiry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshExpiry", reflect.TypeOf((*MockService)(nil).GetRefreshExpiry))
}

// ValidateToken mocks base method.
func (m *MockService) ValidateToken(tokenString string) (*jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockServiceMockRecorder) ValidateToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockService)(nil).ValidateToken), tokenString)
}
