FROM --platform=$BUILDPLATFORM golang:1.27.2-alpine AS modules
WORKDIR /modules
COPY go.mod go.sum ./
RUN go mod download

FROM --platform=$BUILDPLATFORM golang:1.27.2-alpine AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /source
COPY --from=modules /go/pkg /go/pkg
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-s -w" -o /bin/app ./cmd/app
RUN mkdir -p /runtime/tmp && chmod 1777 /runtime/tmp

FROM scratch
COPY --from=builder --chown=65532:65532 /source/config /config
COPY --from=builder --chown=65532:65532 /runtime/ /
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
USER 65532:65532
CMD ["/app"]
