// Code generated by MockGen. DO NOT EDIT.
// Source: mock implementations for media handler tests

package media_test

import (
	"context"
	"reflect"

	"go-boilerplate/internal/dto/media"
	"go-boilerplate/internal/entity"

	"go.uber.org/mock/gomock"
	"go.uber.org/zap"
)

// MockMedia is a mock of Media interface.
type MockMedia struct {
	ctrl     *gomock.Controller
	recorder *MockMediaMockRecorder
}

// MockMediaMockRecorder is the mock recorder for MockMedia.
type MockMediaMockRecorder struct {
	mock *MockMedia
}

// NewMockMedia creates a new mock instance.
func NewMockMedia(ctrl *gomock.Controller) *MockMedia {
	mock := &MockMedia{ctrl: ctrl}
	mock.recorder = &MockMediaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMedia) EXPECT() *MockMediaMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockMedia) Upload(ctx context.Context, req mediadto.UploadRequest) (*mediadto.MediaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, req)
	ret0, _ := ret[0].(*mediadto.MediaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockMediaMockRecorder) Upload(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockMedia)(nil).Upload), ctx, req)
}

// GetByID mocks base method.
func (m *MockMedia) GetByID(ctx context.Context, id uint) (*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMedia)(nil).GetByID), ctx, id)
}

// GetByAttachable mocks base method.
func (m *MockMedia) GetByAttachable(ctx context.Context, req mediadto.GetMediaRequest) (*mediadto.MediaListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAttachable", ctx, req)
	ret0, _ := ret[0].(*mediadto.MediaListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAttachable indicates an expected call of GetByAttachable.
func (mr *MockMediaMockRecorder) GetByAttachable(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAttachable", reflect.TypeOf((*MockMedia)(nil).GetByAttachable), ctx, req)
}

// GetURL mocks base method.
func (m *MockMedia) GetURL(ctx context.Context, media *entity.Media, variant string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, media, variant)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockMediaMockRecorder) GetURL(ctx, media, variant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockMedia)(nil).GetURL), ctx, media, variant)
}

// GetPresignedUploadURL mocks base method.
func (m *MockMedia) GetPresignedUploadURL(ctx context.Context, filename string) (*mediadto.PresignedURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedUploadURL", ctx, filename)
	ret0, _ := ret[0].(*mediadto.PresignedURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedUploadURL indicates an expected call of GetPresignedUploadURL.
func (mr *MockMediaMockRecorder) GetPresignedUploadURL(ctx, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedUploadURL", reflect.TypeOf((*MockMedia)(nil).GetPresignedUploadURL), ctx, filename)
}

// Delete mocks base method.
func (m *MockMedia) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMedia)(nil).Delete), ctx, id)
}

// MockLogger is a mock of logger.Interface.
type MockLogger struct{}

func NewMockLogger() *MockLogger {
	return &MockLogger{}
}

func (m *MockLogger) Debug(message interface{}, args ...interface{}) {}
func (m *MockLogger) Info(message string, args ...interface{})       {}
func (m *MockLogger) Warn(message string, args ...interface{})       {}
func (m *MockLogger) Error(message interface{}, args ...interface{}) {}
func (m *MockLogger) Fatal(message interface{}, args ...interface{}) {}
func (m *MockLogger) GetZapLogger() *zap.Logger                      { return nil }
