package wire

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// scanFeatures scans internal/usecase/*/ for directories containing a Go file
// with a New() constructor function AND companion generated artifacts (handler,
// DTO, repo, entity). This filters out manually-created features like auth/media
// that don't follow the generated CRUD pattern.
func scanFeatures(outputDir string) ([]Feature, error) {
	usecaseDir := filepath.Join(outputDir, "internal", "usecase")

	entries, err := os.ReadDir(usecaseDir)
	if err != nil {
		return nil, fmt.Errorf("reading usecase directory: %w", err)
	}

	var features []Feature
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		name := entry.Name()
		pkgDir := filepath.Join(usecaseDir, name)

		if !hasNewConstructor(pkgDir) {
			continue
		}

		entityName := toPascalCase(name)

		// Only consider features that have all generated CRUD artifacts
		if !hasGeneratedArtifacts(outputDir, name, entityName) {
			continue
		}

		features = append(features, Feature{
			Name:        name,
			EntityName:  entityName,
			PackageName: name,
			VarName:     toCamelCase(name),
		})
	}

	return features, nil
}

// hasNewConstructor checks if any .go file in the directory contains a "func New(" declaration.
func hasNewConstructor(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		// Skip test files
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			continue
		}

		if strings.Contains(string(content), "func New(") {
			return true
		}
	}

	return false
}

// hasGeneratedArtifacts checks that a feature has companion handler directory,
// DTO directory, and persistent repo file — indicating it was generated by the
// code generator and follows the CRUD pattern.
func hasGeneratedArtifacts(outputDir, pkgName, _ string) bool {
	// Check handler directory exists
	handlerDir := filepath.Join(outputDir, "internal", "handlers", "http", "v1", pkgName)
	if _, err := os.Stat(handlerDir); os.IsNotExist(err) {
		return false
	}

	// Check DTO directory exists
	dtoDir := filepath.Join(outputDir, "internal", "dto", pkgName)
	if _, err := os.Stat(dtoDir); os.IsNotExist(err) {
		return false
	}

	// Check persistent repo file exists (named {pkgName}.go or has New{EntityName}Repo)
	repoFile := filepath.Join(outputDir, "internal", "repo", "persistent", pkgName+".go")
	if _, err := os.Stat(repoFile); os.IsNotExist(err) {
		return false
	}

	return true
}

// findUnwired returns features that are missing from ANY of the target files.
func findUnwired(outputDir string, features []Feature) ([]Feature, error) {
	repoContracts, err := readFileContent(outputDir, "internal/repo/contracts.go")
	if err != nil {
		return nil, fmt.Errorf("reading repo contracts: %w", err)
	}

	usecaseContracts, err := readFileContent(outputDir, "internal/usecase/contracts.go")
	if err != nil {
		return nil, fmt.Errorf("reading usecase contracts: %w", err)
	}

	routerContent, err := readFileContent(outputDir, "internal/handlers/http/router.go")
	if err != nil {
		return nil, fmt.Errorf("reading router: %w", err)
	}

	appContent, err := readFileContent(outputDir, "internal/app/app.go")
	if err != nil {
		return nil, fmt.Errorf("reading app.go: %w", err)
	}

	var unwired []Feature
	for _, f := range features {
		if isUnwired(f, repoContracts, usecaseContracts, routerContent, appContent) {
			unwired = append(unwired, f)
		}
	}

	return unwired, nil
}

// isUnwired checks if a feature is missing from any of the target files.
func isUnwired(f Feature, repoContracts, usecaseContracts, routerContent, appContent string) bool {
	// Check repo contracts for {EntityName}Repo interface
	if !strings.Contains(repoContracts, f.EntityName+"Repo interface") {
		return true
	}

	// Check usecase contracts for {EntityName} interface
	if !strings.Contains(usecaseContracts, f.EntityName+" interface") {
		return true
	}

	// Check router for handler import (using the handler alias pattern)
	handlerImport := fmt.Sprintf(`/v1/%s"`, f.PackageName)
	if !strings.Contains(routerContent, handlerImport) {
		return true
	}

	// Check app.go for field in repositories struct
	// Use flexible whitespace matching since Go struct fields may have aligned spacing
	repoField := "repo." + f.EntityName + "Repo"
	return !strings.Contains(appContent, repoField)
}

// readFileContent reads a file relative to outputDir and returns its content as a string.
func readFileContent(outputDir, relPath string) (string, error) {
	fullPath := filepath.Join(outputDir, relPath)
	content, err := os.ReadFile(fullPath)
	if err != nil {
		return "", err
	}
	return string(content), nil
}
