// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=../usecase/mocks_repo_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	articledto "go-boilerplate/internal/dto/article"
	translationdto "go-boilerplate/internal/dto/translation"
	entity "go-boilerplate/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, req translationdto.HistoryRequest) ([]entity.Translation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, req)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, req)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(arg0 context.Context, arg1 *entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), arg0, arg1)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 *entity.Translation) (*entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(*entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepo) Create(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepo)(nil).Create), ctx, user)
}

// EmailExists mocks base method.
func (m *MockUserRepo) EmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailExists indicates an expected call of EmailExists.
func (mr *MockUserRepoMockRecorder) EmailExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailExists", reflect.TypeOf((*MockUserRepo)(nil).EmailExists), ctx, email)
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id uint) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepo) Update(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepoMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepo)(nil).Update), ctx, user)
}

// MockRoleRepo is a mock of RoleRepo interface.
type MockRoleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepoMockRecorder
	isgomock struct{}
}

// MockRoleRepoMockRecorder is the mock recorder for MockRoleRepo.
type MockRoleRepoMockRecorder struct {
	mock *MockRoleRepo
}

// NewMockRoleRepo creates a new mock instance.
func NewMockRoleRepo(ctrl *gomock.Controller) *MockRoleRepo {
	mock := &MockRoleRepo{ctrl: ctrl}
	mock.recorder = &MockRoleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepo) EXPECT() *MockRoleRepoMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockRoleRepo) GetByName(ctx context.Context, name string) (*entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockRoleRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockRoleRepo)(nil).GetByName), ctx, name)
}

// MockRefreshTokenRepo is a mock of RefreshTokenRepo interface.
type MockRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepoMockRecorder is the mock recorder for MockRefreshTokenRepo.
type MockRefreshTokenRepoMockRecorder struct {
	mock *MockRefreshTokenRepo
}

// NewMockRefreshTokenRepo creates a new mock instance.
func NewMockRefreshTokenRepo(ctrl *gomock.Controller) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepo) Create(ctx context.Context, token *entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepoMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Create), ctx, token)
}

// DeleteByToken mocks base method.
func (m *MockRefreshTokenRepo) DeleteByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByToken indicates an expected call of DeleteByToken.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByToken", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByToken), ctx, token)
}

// DeleteByUserID mocks base method.
func (m *MockRefreshTokenRepo) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockRefreshTokenRepo) GetByToken(ctx context.Context, token string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockRefreshTokenRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockRefreshTokenRepo)(nil).GetByToken), ctx, token)
}

// MockMediaRepo is a mock of MediaRepo interface.
type MockMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepoMockRecorder
	isgomock struct{}
}

// MockMediaRepoMockRecorder is the mock recorder for MockMediaRepo.
type MockMediaRepoMockRecorder struct {
	mock *MockMediaRepo
}

// NewMockMediaRepo creates a new mock instance.
func NewMockMediaRepo(ctrl *gomock.Controller) *MockMediaRepo {
	mock := &MockMediaRepo{ctrl: ctrl}
	mock.recorder = &MockMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepo) EXPECT() *MockMediaRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMediaRepo) Create(ctx context.Context, media *entity.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMediaRepoMockRecorder) Create(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMediaRepo)(nil).Create), ctx, media)
}

// Delete mocks base method.
func (m *MockMediaRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaRepo)(nil).Delete), ctx, id)
}

// DeleteByAttachable mocks base method.
func (m *MockMediaRepo) DeleteByAttachable(ctx context.Context, attachableType string, attachableID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAttachable", ctx, attachableType, attachableID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAttachable indicates an expected call of DeleteByAttachable.
func (mr *MockMediaRepoMockRecorder) DeleteByAttachable(ctx, attachableType, attachableID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAttachable", reflect.TypeOf((*MockMediaRepo)(nil).DeleteByAttachable), ctx, attachableType, attachableID)
}

// GetByAttachable mocks base method.
func (m *MockMediaRepo) GetByAttachable(ctx context.Context, attachableType string, attachableID uint, collection string) ([]*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAttachable", ctx, attachableType, attachableID, collection)
	ret0, _ := ret[0].([]*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAttachable indicates an expected call of GetByAttachable.
func (mr *MockMediaRepoMockRecorder) GetByAttachable(ctx, attachableType, attachableID, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAttachable", reflect.TypeOf((*MockMediaRepo)(nil).GetByAttachable), ctx, attachableType, attachableID, collection)
}

// GetByID mocks base method.
func (m *MockMediaRepo) GetByID(ctx context.Context, id uint) (*entity.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMediaRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockMediaRepo) Update(ctx context.Context, media *entity.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMediaRepoMockRecorder) Update(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMediaRepo)(nil).Update), ctx, media)
}

// MockEmailVerificationRepo is a mock of EmailVerificationRepo interface.
type MockEmailVerificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepoMockRecorder
	isgomock struct{}
}

// MockEmailVerificationRepoMockRecorder is the mock recorder for MockEmailVerificationRepo.
type MockEmailVerificationRepoMockRecorder struct {
	mock *MockEmailVerificationRepo
}

// NewMockEmailVerificationRepo creates a new mock instance.
func NewMockEmailVerificationRepo(ctrl *gomock.Controller) *MockEmailVerificationRepo {
	mock := &MockEmailVerificationRepo{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepo) EXPECT() *MockEmailVerificationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailVerificationRepo) Create(ctx context.Context, verification *entity.EmailVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, verification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationRepoMockRecorder) Create(ctx, verification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationRepo)(nil).Create), ctx, verification)
}

// DeleteByUserID mocks base method.
func (m *MockEmailVerificationRepo) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockEmailVerificationRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockEmailVerificationRepo)(nil).DeleteByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockEmailVerificationRepo) GetByToken(ctx context.Context, token string) (*entity.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*entity.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockEmailVerificationRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockEmailVerificationRepo)(nil).GetByToken), ctx, token)
}

// GetLatestByUserID mocks base method.
func (m *MockEmailVerificationRepo) GetLatestByUserID(ctx context.Context, userID uint) (*entity.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUserID indicates an expected call of GetLatestByUserID.
func (mr *MockEmailVerificationRepoMockRecorder) GetLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUserID", reflect.TypeOf((*MockEmailVerificationRepo)(nil).GetLatestByUserID), ctx, userID)
}

// MarkAsUsed mocks base method.
func (m *MockEmailVerificationRepo) MarkAsUsed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockEmailVerificationRepoMockRecorder) MarkAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockEmailVerificationRepo)(nil).MarkAsUsed), ctx, id)
}

// MockPasswordResetRepo is a mock of PasswordResetRepo interface.
type MockPasswordResetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepoMockRecorder
	isgomock struct{}
}

// MockPasswordResetRepoMockRecorder is the mock recorder for MockPasswordResetRepo.
type MockPasswordResetRepoMockRecorder struct {
	mock *MockPasswordResetRepo
}

// NewMockPasswordResetRepo creates a new mock instance.
func NewMockPasswordResetRepo(ctrl *gomock.Controller) *MockPasswordResetRepo {
	mock := &MockPasswordResetRepo{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepo) EXPECT() *MockPasswordResetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetRepo) Create(ctx context.Context, reset *entity.PasswordReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetRepoMockRecorder) Create(ctx, reset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetRepo)(nil).Create), ctx, reset)
}

// DeleteByUserID mocks base method.
func (m *MockPasswordResetRepo) DeleteByUserID(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockPasswordResetRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockPasswordResetRepo)(nil).DeleteByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockPasswordResetRepo) GetByToken(ctx context.Context, token string) (*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockPasswordResetRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockPasswordResetRepo)(nil).GetByToken), ctx, token)
}

// MarkAsUsed mocks base method.
func (m *MockPasswordResetRepo) MarkAsUsed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockPasswordResetRepoMockRecorder) MarkAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockPasswordResetRepo)(nil).MarkAsUsed), ctx, id)
}

// MockProfileRepo is a mock of ProfileRepo interface.
type MockProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepoMockRecorder
	isgomock struct{}
}

// MockProfileRepoMockRecorder is the mock recorder for MockProfileRepo.
type MockProfileRepoMockRecorder struct {
	mock *MockProfileRepo
}

// NewMockProfileRepo creates a new mock instance.
func NewMockProfileRepo(ctrl *gomock.Controller) *MockProfileRepo {
	mock := &MockProfileRepo{ctrl: ctrl}
	mock.recorder = &MockProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepo) EXPECT() *MockProfileRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProfileRepo) Create(ctx context.Context, profile *entity.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProfileRepoMockRecorder) Create(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProfileRepo)(nil).Create), ctx, profile)
}

// GetByUserID mocks base method.
func (m *MockProfileRepo) GetByUserID(ctx context.Context, userID uint) (*entity.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockProfileRepoMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockProfileRepo)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockProfileRepo) Update(ctx context.Context, profile *entity.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProfileRepoMockRecorder) Update(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProfileRepo)(nil).Update), ctx, profile)
}

// Upsert mocks base method.
func (m *MockProfileRepo) Upsert(ctx context.Context, profile *entity.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProfileRepoMockRecorder) Upsert(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProfileRepo)(nil).Upsert), ctx, profile)
}

// MockArticleRepo is a mock of ArticleRepo interface.
type MockArticleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepoMockRecorder
	isgomock struct{}
}

// MockArticleRepoMockRecorder is the mock recorder for MockArticleRepo.
type MockArticleRepoMockRecorder struct {
	mock *MockArticleRepo
}

// NewMockArticleRepo creates a new mock instance.
func NewMockArticleRepo(ctrl *gomock.Controller) *MockArticleRepo {
	mock := &MockArticleRepo{ctrl: ctrl}
	mock.recorder = &MockArticleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepo) EXPECT() *MockArticleRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockArticleRepo) Create(ctx context.Context, arg1 *entity.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockArticleRepoMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArticleRepo)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockArticleRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockArticleRepo) GetByID(ctx context.Context, id uint) (*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockArticleRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockArticleRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockArticleRepo) List(ctx context.Context, req articledto.ListRequest) ([]*entity.Article, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]*entity.Article)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockArticleRepoMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArticleRepo)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockArticleRepo) Update(ctx context.Context, arg1 *entity.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockArticleRepoMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArticleRepo)(nil).Update), ctx, arg1)
}
