// Code generated by MockGen. DO NOT EDIT.
// Source: mock implementations for article handler tests

package article_test

import (
	"context"
	"reflect"
	"time"

	articledto "go-boilerplate/internal/dto/article"
	"go-boilerplate/pkg/jwt"

	"go.uber.org/mock/gomock"
	"go.uber.org/zap"
)

// MockArticle is a mock of Article interface.
type MockArticle struct {
	ctrl     *gomock.Controller
	recorder *MockArticleMockRecorder
}

// MockArticleMockRecorder is the mock recorder for MockArticle.
type MockArticleMockRecorder struct {
	mock *MockArticle
}

// NewMockArticle creates a new mock instance.
func NewMockArticle(ctrl *gomock.Controller) *MockArticle {
	mock := &MockArticle{ctrl: ctrl}
	mock.recorder = &MockArticleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticle) EXPECT() *MockArticleMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockArticle) Create(ctx context.Context, userID uint, req articledto.CreateRequest) (*articledto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, req)
	ret0, _ := ret[0].(*articledto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockArticleMockRecorder) Create(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArticle)(nil).Create), ctx, userID, req)
}

// GetByID mocks base method.
func (m *MockArticle) GetByID(ctx context.Context, id uint) (*articledto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*articledto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockArticleMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockArticle)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockArticle) List(ctx context.Context, req articledto.ListRequest) (*articledto.ListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*articledto.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockArticleMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArticle)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockArticle) Update(ctx context.Context, userID uint, id uint, req articledto.UpdateRequest) (*articledto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, id, req)
	ret0, _ := ret[0].(*articledto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockArticleMockRecorder) Update(ctx, userID, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArticle)(nil).Update), ctx, userID, id, req)
}

// Delete mocks base method.
func (m *MockArticle) Delete(ctx context.Context, userID uint, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleMockRecorder) Delete(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticle)(nil).Delete), ctx, userID, id)
}

// MockLogger is a mock of logger.Interface.
type MockLogger struct{}

func NewMockLogger() *MockLogger {
	return &MockLogger{}
}

func (m *MockLogger) Debug(message interface{}, args ...interface{}) {}
func (m *MockLogger) Info(message string, args ...interface{})       {}
func (m *MockLogger) Warn(message string, args ...interface{})       {}
func (m *MockLogger) Error(message interface{}, args ...interface{}) {}
func (m *MockLogger) Fatal(message interface{}, args ...interface{}) {}
func (m *MockLogger) GetZapLogger() *zap.Logger                      { return nil }

// MockJWTService is a mock of jwt.Service for testing.
type MockJWTService struct{}

func NewMockJWTService() *MockJWTService {
	return &MockJWTService{}
}

func (m *MockJWTService) GenerateAccessToken(userID uint, email, role string, permissions []string) (string, int64, error) {
	return "mock-access-token", 9999999999, nil
}

func (m *MockJWTService) GenerateRefreshToken() (string, time.Time, error) {
	return "mock-refresh-token", time.Now().Add(24 * time.Hour), nil
}

func (m *MockJWTService) ValidateToken(tokenString string) (*jwt.Claims, error) {
	return &jwt.Claims{
		UserID:      1,
		Email:       "test@example.com",
		Role:        "admin",
		Permissions: []string{"articles:write"},
	}, nil
}

func (m *MockJWTService) GetAccessExpiry() time.Duration  { return 15 * time.Minute }
func (m *MockJWTService) GetRefreshExpiry() time.Duration { return 24 * time.Hour }
